start:
  name: Start Timer
  description: Start the Ontime timer

pause:
  name: Pause Timer
  description: Pause the Ontime timer

stop:
  name: Stop Timer
  description: Stop the Ontime timer

reload:
  name: Reload
  description: Reload the current event

roll:
  name: Roll
  description: Activate roll mode (sync to schedule)

load_event:
  name: Load Event
  description: Load a specific event by ID
  fields:
    event_id:
      name: Event ID
      description: The ID of the event to load
      required: true
      example: "abc123"
      selector:
        text:

start_event:
  name: Start Event
  description: Load and start a specific event by ID
  fields:
    event_id:
      name: Event ID
      description: The ID of the event to start
      required: true
      example: "abc123"
      selector:
        text:

add_time:
  name: Add Time
  description: Add or subtract time from the timer
  fields:
    time:
      name: Time
      description: Time to add in milliseconds (use negative values to subtract)
      required: true
      example: 60000
      selector:
        number:
          min: -3600000
          max: 3600000
          unit_of_measurement: "ms"
    direction:
      name: Direction
      description: Which action to perform (add or remove time)
      required: false
      default: add
      selector:
        select:
          options:
            - add
            - remove
            - subtract

load_event_index:
  name: Load Event by Index
  description: Load an event by its index in the rundown
  fields:
    event_index:
      name: Event Index
      description: The index of the event to load (1-based)
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 1000
          mode: box

load_event_cue:
  name: Load Event by Cue
  description: Load an event by its cue name
  fields:
    event_cue:
      name: Event Cue
      description: The cue name of the event to load
      required: true
      example: "Q1"
      selector:
        text:
