name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create ZIP
        run: |
          cd custom_components/ontime
          zip -r ../../ontime-ha.zip .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ontime-ha.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
